feat: update to latest Zig
silversquirl/binaryen-zig pull request #1
Opened 2023-09-21 03:13 UTC by ianprime0509

Thanks for this project! This might end up being useful for a project I'm working on, so I wanted to get it working on the latest master version of Zig; this is the result I came up with.

2023-09-22 19:03 UTC, silversquirl requested changes
Thanks for the PR! Looks great, just a couple small style changes and I'll merge :)

2023-09-22 19:03 UTC, silversquirl commented on binaryen.zig
> +            .binary = @as([*]u8, @ptrCast(result.binary))[0..result.binaryBytes],
Cleaner to split this into a separate `binary_ptr` variable with a type annotation, rather than using `@as`

2023-09-22 19:03 UTC, silversquirl commented on build.zig
> +    lib.addCSourceFile(.{ .file = .{ .path = "src/binaryen-c.cpp" }, .flags = flags });
I'd split this onto multiple lines :)

2023-09-23 01:09 UTC, ianprime0509 commented
Thanks! I applied both requested changes 😄

2023-09-24 15:39 UTC, merged